server {
    listen 80;

    location /the-wine-corner/ {
        alias /usr/share/nginx/html/the-wine-corner/;
        try_files $uri $uri/ /the-wine-corner/index.html;
    }

    # Redirect root to /the-wine-corner/
    location = / {
        return 301 /the-wine-corner/;
    }
}
