server {
    listen 80;
    absolute_redirect off;

    root /usr/share/nginx/html;

    location /the-wine-corner/ {
        try_files $uri $uri/ /the-wine-corner/index.html;
    }

    # Redirect root to /the-wine-corner/
    location = / {
        return 301 /the-wine-corner/;
    }
}
